language: go
sudo: false
go:
  - 1.5.4
  - 1.6.1
  - tip
install: true
env:
  global:
    - GO15VENDOREXPERIMENT=1
script:
    - go clean ./...
    - go test ./...
matrix:
  allow_failures:
    - go: tip
